// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9bMwsYVt1rMrJonvwNOZlEfwZ5-fmMWY',
    appId: '1:70132739234:web:5dd5edc769a9a03adf3bfb',
    messagingSenderId: '70132739234',
    projectId: 'rifqial-31d31',
    authDomain: 'rifqial-31d31.firebaseapp.com',
    storageBucket: 'rifqial-31d31.appspot.com',
    measurementId: 'G-XWFWPZ5SW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQpSJKnXwkPmEgzc3UP8XCNpdZGbWsr2g',
    appId: '1:70132739234:android:a5fde3198b531cb3df3bfb',
    messagingSenderId: '70132739234',
    projectId: 'rifqial-31d31',
    storageBucket: 'rifqial-31d31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsP5zKgm2C9uBG3KClOmqeAwYXVKBR_14',
    appId: '1:70132739234:ios:495c7f1a20e53b51df3bfb',
    messagingSenderId: '70132739234',
    projectId: 'rifqial-31d31',
    storageBucket: 'rifqial-31d31.appspot.com',
    iosClientId: '70132739234-2voutrcl5vth3l6hlv1u8j7kqttko2rc.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasFp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsP5zKgm2C9uBG3KClOmqeAwYXVKBR_14',
    appId: '1:70132739234:ios:495c7f1a20e53b51df3bfb',
    messagingSenderId: '70132739234',
    projectId: 'rifqial-31d31',
    storageBucket: 'rifqial-31d31.appspot.com',
    iosClientId: '70132739234-2voutrcl5vth3l6hlv1u8j7kqttko2rc.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasFp',
  );
}
